<?php 

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
if (isset($_POST["submit"])) {

	$amount = $_POST["amount"];
	$name = $_POST["name"];
	$order = $_POST["order"];

	// $rand_token = "1973516717aa";
	$rand_token = md5(rand(10000, 10000000000000000));
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://komoju.com/api/v1/sessions');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "default_locale=ja&email=test@example.com&metadata[test]=value&amount=".$amount."&currency=JPY&payment_data[external_order_num]=".$rand_token."&payment_data[name]=".$name."&return_url=http://localhost/gaijinmall-v3/gaijinmall/views/test.php");

	curl_setopt($ch, CURLOPT_USERPWD, 'sk_test_2zowjs6bxxmjjl3np1huex10' . ':' . '');

	$headers = array();
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	// if (curl_errno($ch)) {
	//     echo 'Error:' . curl_error($ch);
	// }
	curl_close($ch);

	$data = json_decode($result, true);
	// var_dump($data);
	$url = $data["session_url"];
	header("location:".$url);


	print_r($_POST);
}

if (isset($_GET["session_id"])) {
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://komoju.com/api/v1/sessions/'.$_GET["session_id"]);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

	curl_setopt($ch, CURLOPT_USERPWD, 'sk_test_2zowjs6bxxmjjl3np1huex10' . ':' . '');

	$result = curl_exec($ch);
	// if (curl_errno($ch)) {
	//     echo 'Error:' . curl_error($ch);
	// }
	curl_close($ch);
	$data = json_decode($result, true);
	$status = $data["status"];
	print "<pre>";
	print_r($data);
	print "</pre>";
	// echo "<pre>". var_dump($data) ."</pre>";
	echo "<br>";
	var_dump($status);
	echo "<br>";

	
}
$n = 100;
echo "hello, $n";
	
?>

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<!-- <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"> -->
</head>
<body>
	<h1>TEST CASE</h1>
	<main>
		<form method="POST" >
			<input type="number" name="amount" value="100">
			<input type="number" name="order" value="30">
			<input type="" name="name" value="John Doe">
			<button type="submit" name="submit">Submit</button>
		</form>
	</main>
	
</body>
</html>
